# Generated by Django 5.2.15 on 2026-06-10 18:13

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('product_type', models.CharField(choices=[('Tshirt', 'Tshirt')], default='Tshirt', max_length=60)),
                ('sub_category', models.CharField(choices=[('Regular', 'Regular')], default='Regular', max_length=60)),
                ('has_variants', models.BooleanField(default=False)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('received', 'Received')], default='draft', max_length=20)),
                ('print_pack_path', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='shopify', max_length=40)),
                ('topic', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankSKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabric', models.CharField(max_length=120)),
                ('colour', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=30)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('reorder_min', models.IntegerField(default=0)),
                ('reorder_target', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['fabric', 'colour', 'size'],
                'constraints': [models.UniqueConstraint(fields=('fabric', 'colour', 'size'), name='uniq_blanksku_fabric_colour_size')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_order_id', models.CharField(max_length=80, unique=True)),
                ('order_no', models.CharField(blank=True, max_length=80)),
                ('customer_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('needs_printing', 'Needs Printing'), ('in_printing', 'In Printing'), ('ready_to_ship', 'Ready To Ship'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('issue', 'Issue')], default='new', max_length=30)),
                ('shopify_fulfillment_status', models.CharField(blank=True, max_length=80)),
                ('shopify_delivery_status', models.CharField(blank=True, max_length=80)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='order_status_idx'), models.Index(fields=['created_at'], name='order_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopify_line_id', models.CharField(max_length=80, unique=True)),
                ('product_name', models.CharField(max_length=220)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('is_bundle', models.BooleanField(default=False)),
                ('bundle_components', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('to_be_printed', 'To Be Printed'), ('in_printing', 'In Printing'), ('ready_ship', 'Ready to Ship'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.order')),
            ],
            options={
                'ordering': ['created_at', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='PrintedSKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(blank=True, max_length=120, null=True)),
                ('colour', models.CharField(max_length=60)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('buffer_min', models.IntegerField(default=0)),
                ('buffer_target', models.IntegerField(default=0)),
                ('buffer_max', models.IntegerField(default=0)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printed_skus', to='core.design')),
            ],
            options={
                'ordering': ['design__name', 'variant', 'colour', 'size'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_each', models.IntegerField(default=1)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.orderline')),
                ('printed_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_components', to='core.printedsku')),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='printed_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='core.printedsku'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True, max_length=600)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='core.printbatch')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='core.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJobLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_sent', models.IntegerField(default=0)),
                ('qty_received_good', models.IntegerField(default=0)),
                ('qty_received_defective', models.IntegerField(default=0)),
                ('shortfall_flagged', models.BooleanField(default=False)),
                ('blank_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_job_lines', to='core.blanksku')),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.printjob')),
                ('printed_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_job_lines', to='core.printedsku')),
            ],
        ),
        migrations.CreateModel(
            name='ReprintTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('printed_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprint_tasks', to='core.printedsku')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_tasks', to='core.printjobline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.CharField(choices=[('plain', 'Plain'), ('printed', 'Printed')], max_length=20)),
                ('delta_on_hand', models.IntegerField(default=0)),
                ('delta_reserved', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('adjustment', 'Adjustment'), ('soft_reserve', 'Soft Reserve'), ('release_reservation', 'Release Reservation'), ('ship', 'Ship'), ('print_batch_confirm', 'Print Batch Confirm'), ('print_receive', 'Print Receive'), ('cancel', 'Cancel'), ('reprint', 'Reprint'), ('import', 'Import')], max_length=40)),
                ('ref_table', models.CharField(blank=True, max_length=80)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('blank_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.blanksku')),
                ('printed_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.printedsku')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colour', models.CharField(max_length=60)),
                ('artwork_url', models.URLField(max_length=600)),
                ('mockup_url', models.URLField(max_length=600)),
                ('blank_fabric', models.CharField(max_length=120)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.design')),
            ],
            options={
                'ordering': ['design__name', 'colour'],
                'constraints': [models.UniqueConstraint(fields=('design', 'colour'), name='uniq_designasset_design_colour')],
            },
        ),
        migrations.AddConstraint(
            model_name='printedsku',
            constraint=models.UniqueConstraint(models.F('design'), django.db.models.functions.comparison.Coalesce('variant', models.Value('')), models.F('colour'), django.db.models.functions.comparison.Coalesce('size', models.Value('')), name='uniq_printedsku_design_variant_colour_size'),
        ),
        migrations.AddConstraint(
            model_name='orderlinecomponent',
            constraint=models.UniqueConstraint(fields=('order_line', 'printed_sku'), name='uniq_orderlinecomponent_line_sku'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['status'], name='orderline_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='printjobline',
            constraint=models.UniqueConstraint(fields=('print_job', 'printed_sku'), name='uniq_printjobline_job_sku'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('blank_sku__isnull', False), ('printed_sku__isnull', False), _connector='OR'), name='stockmovement_has_target_sku'),
        ),
    ]
