# Generated by Django 5.2.15 on 2026-06-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='fit',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Oversized', 'Oversized')], default='Regular', max_length=30),
        ),
        migrations.AddField(
            model_name='design',
            name='material',
            field=models.CharField(default='Cotton', max_length=60),
        ),
        migrations.AddField(
            model_name='designasset',
            name='colour_hex',
            field=models.CharField(blank=True, help_text='Hex colour for the swatch on the print pack, e.g. #1b1b1b.', max_length=7),
        ),
        migrations.AddField(
            model_name='designasset',
            name='placement_note',
            field=models.TextField(blank=True, help_text="Placement instructions for the printer, e.g. 'Artwork must be placed at the chest'."),
        ),
        migrations.AddField(
            model_name='designasset',
            name='print_areas',
            field=models.CharField(blank=True, help_text="Print location shown on the pack, e.g. 'Front' or 'Front (Chest)'.", max_length=120),
        ),
    ]
