# Generated by Django 5.2.15 on 2026-06-11 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_design_fit_design_material_designasset_colour_hex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField()),
                ('withdrawals', models.IntegerField(default=0)),
                ('deposits', models.IntegerField(default=0)),
                ('cheque_no', models.CharField(blank=True, max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=255)),
                ('entity', models.CharField(blank=True, max_length=120)),
                ('person', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('match_confidence', models.CharField(choices=[('auto_reconciled', 'Auto-Reconciled'), ('needs_review', 'Needs Review'), ('manual_matched', 'Manual Match')], default='needs_review', max_length=50)),
                ('running_balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_date'], name='txn_date_idx'), models.Index(fields=['reference_no'], name='txn_reference_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('paid_by', models.CharField(max_length=120)),
                ('entity', models.CharField(max_length=120)),
                ('person', models.CharField(blank=True, max_length=120)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['status'], name='expense_status_idx'), models.Index(fields=['expense_date'], name='expense_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_type', models.CharField(choices=[('tax_invoice', 'Tax Invoice'), ('proforma', 'Proforma Invoice')], default='tax_invoice', max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('order_date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('client_address', models.TextField()),
                ('client_gstin', models.CharField(blank=True, max_length=20)),
                ('place_of_supply', models.CharField(choices=[('telangana', 'Telangana'), ('maharashtra', 'Maharashtra'), ('karnataka', 'Karnataka'), ('delhi', 'Delhi'), ('others', 'Others (IGST)')], default='telangana', max_length=30)),
                ('discount_amount', models.IntegerField(default=0)),
                ('deductions_amount', models.IntegerField(default=0)),
                ('subtotal_amount', models.IntegerField(default=0)),
                ('net_taxable_amount', models.IntegerField(default=0)),
                ('tax_amount', models.IntegerField(default=0)),
                ('grand_total_amount', models.IntegerField(default=0)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['invoice_number'], name='inv_number_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('hsn_sac', models.CharField(blank=True, max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.invoice')),
            ],
            options={
                'ordering': ['invoice', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='core.banktransaction')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='core.expense')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
