# Generated by Django 5.2.15 on 2026-08-18 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_datetime


PAYLOAD_TO_FIELD = {
    "created_at": "shopify_created_at",
    "updated_at": "shopify_updated_at",
    "cancelled_at": "cancelled_at",
}


def _parse(value):
    """Parse a Shopify ISO timestamp into an aware datetime, or None."""
    if not value or not isinstance(value, str):
        return None
    parsed = parse_datetime(value)
    if parsed is None:
        return None
    if timezone.is_naive(parsed):
        return timezone.make_aware(parsed, timezone.get_default_timezone())
    return parsed


def backfill_shopify_dates(apps, schema_editor):
    """Recover real Shopify order dates from the stored raw payloads.

    Historical orders were imported by a bulk backfill, so their created_at is the import
    timestamp. The Shopify payload kept on each row still has the true dates.
    """
    Order = apps.get_model("core", "Order")
    fields = list(PAYLOAD_TO_FIELD.values())
    batch = []
    queryset = Order.objects.only("id", "raw_payload", *fields)
    for order in queryset.iterator(chunk_size=500):
        payload = order.raw_payload if isinstance(order.raw_payload, dict) else {}
        changed = False
        for payload_key, field_name in PAYLOAD_TO_FIELD.items():
            parsed = _parse(payload.get(payload_key))
            if parsed is not None and getattr(order, field_name) is None:
                setattr(order, field_name, parsed)
                changed = True
        if changed:
            batch.append(order)
        if len(batch) >= 500:
            Order.objects.bulk_update(batch, fields)
            batch = []
    if batch:
        Order.objects.bulk_update(batch, fields)


def clear_shopify_dates(apps, schema_editor):
    """Reverse step: the columns are dropped by the AddField reversals anyway."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_designassetfile_and_refactor_printedsku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designassetfile',
            options={'ordering': ['design_asset__design__name', 'design_asset__colour', 'file_type', 'placement']},
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_created_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the customer placed the order in Shopify (created_at is when BoldERP imported it).', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shopify_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printedsku',
            name='blank_sku',
            field=models.ForeignKey(blank=True, help_text='Explicitly linked plain blank SKU. When design_asset is set, blank_sku is auto-populated from design_asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_skus', to='core.blanksku'),
        ),
        migrations.CreateModel(
            name='ProductNameAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(help_text='Raw Shopify product title, kept for display.', max_length=220)),
                ('source_variant', models.CharField(blank=True, max_length=120)),
                ('canonical_name', models.CharField(db_index=True, help_text='Punctuation/case-stripped product title used for lookup.', max_length=220)),
                ('canonical_variant', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, help_text='Target printed SKU variant, blank for base.', max_length=120)),
                ('colour', models.CharField(blank=True, help_text='Target printed SKU colour family.', max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_name_aliases', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_aliases', to='core.design')),
            ],
            options={
                'ordering': ['source_name', 'source_variant'],
                'constraints': [models.UniqueConstraint(fields=('canonical_name', 'canonical_variant'), name='uniq_productnamealias_canonical')],
            },
        ),
        migrations.RunPython(backfill_shopify_dates, clear_shopify_dates),
    ]
